"""add double-entry fields to transactions

Revision ID: b7cf3c40fc52
Revises: c1321c8ac7dd
Create Date: 2026-08-27 12:19:56.937942

Issue #38 (latencia_alta em transaction-service): alem dos campos de
partida dobrada, esta migration tambem cria um indice composto em
(account_id, tipo, created_at). As checagens de risco em
app/services/transaction_risk.py (check_destinatario_novo,
check_velocidade_alta, check_entrada_saida_rapida) filtram por essas
colunas a cada transacao criada; sem indice, cada chamada sincrona faz
sequential scan na tabela inteira e o p95 sobe conforme o volume de
dados cresce (padrao observado pelo agente preditivo: p95 0.096s > 2x
a mediana historica de 0.003s).
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7cf3c40fc52'
down_revision: Union[str, Sequence[str], None] = 'c1321c8ac7dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('e2e_id', sa.UUID(), nullable=False))
    op.add_column('transactions', sa.Column('tipo', sa.String(), nullable=False))
    op.add_column('transactions', sa.Column('contraparte_account_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_transactions_e2e_id'), 'transactions', ['e2e_id'], unique=False)
    # ### end Alembic commands ###

    # issue #38: indice usado pelas checagens de risco (account_id + tipo,
    # com created_at para as janelas de velocidade_alta/entrada_saida_rapida)
    op.create_index(
        op.f('ix_transactions_account_id_tipo_created_at'),
        'transactions',
        ['account_id', 'tipo', 'created_at'],
        unique=False,
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index(op.f('ix_transactions_account_id_tipo_created_at'), table_name='transactions')

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_e2e_id'), table_name='transactions')
    op.drop_column('transactions', 'contraparte_account_id')
    op.drop_column('transactions', 'tipo')
    op.drop_column('transactions', 'e2e_id')
    # ### end Alembic commands ###
