"""add double-entry fields to transactions

Revision ID: b7cf3c40fc52
Revises: c1321c8ac7dd
Create Date: 2026-08-27 12:19:56.937942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7cf3c40fc52'
down_revision: Union[str, Sequence[str], None] = 'c1321c8ac7dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('e2e_id', sa.UUID(), nullable=False))
    op.add_column('transactions', sa.Column('tipo', sa.String(), nullable=False))
    op.add_column('transactions', sa.Column('contraparte_account_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_transactions_e2e_id'), 'transactions', ['e2e_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_e2e_id'), table_name='transactions')
    op.drop_column('transactions', 'contraparte_account_id')
    op.drop_column('transactions', 'tipo')
    op.drop_column('transactions', 'e2e_id')
    # ### end Alembic commands ###
