"""create onboardings table

Revision ID: aae1cb64efdf
Revises: 
Create Date: 2026-08-26 17:22:54.940703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aae1cb64efdf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('onboardings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cpf', sa.String(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('telefone', sa.String(), nullable=False),
    sa.Column('documento_tipo', sa.String(), nullable=False),
    sa.Column('documento_numero', sa.String(), nullable=False),
    sa.Column('dispositivo_id', sa.String(), nullable=False),
    sa.Column('ip_origem', sa.String(), nullable=False),
    sa.Column('status', sa.String(), server_default='em_analise', nullable=False),
    sa.Column('motivo_reprovacao', sa.String(), nullable=True),
    sa.Column('risco_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('risco_sinais', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_onboardings_cpf_unique_not_deleted', 'onboardings', ['cpf'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    # ### end Alembic commands ###

    op.execute(
        """
        CREATE OR REPLACE FUNCTION set_updated_at() RETURNS TRIGGER AS $$
        BEGIN
            NEW.updated_at = now();
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        """
        CREATE TRIGGER onboardings_set_updated_at
        BEFORE UPDATE ON onboardings
        FOR EACH ROW EXECUTE FUNCTION set_updated_at();
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP TRIGGER IF EXISTS onboardings_set_updated_at ON onboardings;")
    op.execute("DROP FUNCTION IF EXISTS set_updated_at();")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_onboardings_cpf_unique_not_deleted', table_name='onboardings', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('onboardings')
    # ### end Alembic commands ###
