"""add tipo_conta to accounts

Revision ID: 07a7ca9877d8
Revises: 16a1176052cd
Create Date: 2026-08-26 18:57:26.465858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07a7ca9877d8'
down_revision: Union[str, Sequence[str], None] = '16a1176052cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('tipo_conta', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'tipo_conta')
    # ### end Alembic commands ###
