"""create accounts table

Revision ID: 16a1176052cd
Revises: 
Create Date: 2026-08-26 17:25:37.228541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '16a1176052cd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('onboarding_id', sa.UUID(), nullable=False),
    sa.Column('cpf', sa.String(), nullable=False),
    sa.Column('status', sa.String(), server_default='ativa', nullable=False),
    sa.Column('risco_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('risco_sinais', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_accounts_cpf', 'accounts', ['cpf'], unique=False)
    # ### end Alembic commands ###

    op.execute(
        """
        CREATE OR REPLACE FUNCTION set_updated_at() RETURNS TRIGGER AS $$
        BEGIN
            NEW.updated_at = now();
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        """
        CREATE TRIGGER accounts_set_updated_at
        BEFORE UPDATE ON accounts
        FOR EACH ROW EXECUTE FUNCTION set_updated_at();
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP TRIGGER IF EXISTS accounts_set_updated_at ON accounts;")
    op.execute("DROP FUNCTION IF EXISTS set_updated_at();")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_accounts_cpf', table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
