"""add saldo to accounts

Revision ID: 9ac3852ce755
Revises: a09b90cb1358
Create Date: 2026-08-27 12:17:10.083205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ac3852ce755'
down_revision: Union[str, Sequence[str], None] = 'a09b90cb1358'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('saldo', sa.Numeric(precision=18, scale=2), server_default='10000.00', nullable=False))
    op.create_check_constraint('ck_accounts_saldo_non_negative', 'accounts', 'saldo >= 0')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_accounts_saldo_non_negative', 'accounts', type_='check')
    op.drop_column('accounts', 'saldo')
    # ### end Alembic commands ###
