"""add unique index on accounts.onboarding_id

Revision ID: c3026cac20e8
Revises: 07a7ca9877d8
Create Date: 2026-08-26 18:58:30.513421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3026cac20e8'
down_revision: Union[str, Sequence[str], None] = '07a7ca9877d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_accounts_onboarding_id_unique_not_deleted', 'accounts', ['onboarding_id'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_accounts_onboarding_id_unique_not_deleted', table_name='accounts', postgresql_where=sa.text('deleted_at IS NULL'))
    # ### end Alembic commands ###
